### ISSUE TITLE
Unexpected behavior of flag aliases and `single` attribute

### ISSUE THREAD

**Issue by gbdrummer** [author/arg#1]
I am creating a new instance of the parser with this config:

```js
query: {
  required: true,
  type: 'string',
  alias: 'q',
  single: true
}
```

When running this command:

`search -query test -q hey`

...I get the following output:

```
data: {
  command: "search"
  args: {
    query: "test"
    q: "hey"
  }
}
```
I expected it to accept the first `-query` arg and ignore `-q`.

---

When running this command:

`search -query test -query hey`

...I get this output:

```
data: {
  command: "search"
  args: {
    query: ["t", "e", "s", "t", "hey"]
  }
}
```

**Comment by gbdrummer** [comment]
I found that I was passing the wrong thing into the parser. My mistake! Closing.

**Comment by coreybutler** [comment]
I would still be curious to know what was being passed to the parser. I could see this potentially being a point of frustration, so perhaps there is something we could add (like an error or something) to help
